inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Rails/HttpPositionalArguments:
  Exclude:
    - spec/requests/**/*

Style/WordArray:
  Exclude:
    - config/**/*.rb
