development:
  secret_key_base: secret
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  os_api_key: <%= ENV['ORDNANCE_SURVEY_PLACES_API_KEY'] %>

test:
  secret_key_base: secret
  os_api_key: <%= ENV['ORDNANCE_SURVEY_PLACES_API_KEY'] || '123' %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  os_api_key: <%= ENV['ORDNANCE_SURVEY_PLACES_API_KEY'] %>
