---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form
      branch: master

  - name: git-master-gems-dockerfile
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form
      branch: master
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-coronavirus-vulnerable-people-tests-image

jobs:
  - name: update-pipeline
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: govuk-corona-vulnerable-people-form
        file: git-master/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-master-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-master-gems-dockerfile
          dockerfile: git-master-gems-dockerfile/concourse/Dockerfile

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed: [build-tests-image]
        trigger: true
      - get: git-master
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-master
          platform: linux
          run:
            dir: git-master
            path: bash
            args:
              - -c
              - |
                set -eu
                wget https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/dynamodb_local_latest.tar.gz
                wget https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/dynamodb_local_latest.tar.gz.sha256
                sha256sum -c <<< "$(awk -F ' ' '{ print $1 }' dynamodb_local_latest.tar.gz.sha256) dynamodb_local_latest.tar.gz"
                tar -xzf dynamodb_local_latest.tar.gz
                java -jar DynamoDBLocal.jar>&1 &
                export RAILS_ENV=test
                bundle install
                bundle exec rake

  - name: deploy-to-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: staging
          INSTANCES: 5
          WORKER_INSTANCES: 1
          CF_STARTUP_TIMEOUT: 5 # minutes
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
          SECRET_KEY_BASE: ((secret-key-base-staging))
          AWS_DYNAMODB_SUBMISSIONS_TABLE_NAME: coronavirus-vulnerable-people-staging
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-vulnerable-people-assets-staging
          HOSTNAME: govuk-coronavirus-vulnerable-people-form-stg

  - name: smoke-test-staging
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-staging]
      - get: tests-image
        passed: [build-tests-image]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          URL: 'https://govuk-coronavirus-vulnerable-people-form-stg.cloudapps.digital/live-in-england'
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
      - task: run-smoke-tests
        file: git-master/concourse/tasks/run-smoke-tests.yml
        params:
          TEST_URL: 'https://gds:((basic-auth-password))@govuk-coronavirus-vulnerable-people-form-stg.cloudapps.digital'

  - name: deploy-to-prod
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [smoke-test-staging]
      - task: deploy-to-paas
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: production
          INSTANCES: 20
          WORKER_INSTANCES: 1
          CF_STARTUP_TIMEOUT: 15 # minutes
          REQUIRE_BASIC_AUTH:
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id-prod))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key-prod))
          SECRET_KEY_BASE: ((secret-key-base-prod))
          AWS_DYNAMODB_SUBMISSIONS_TABLE_NAME: coronavirus-vulnerable-people-prod
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-vulnerable-people-assets-prod
          HOSTNAME: govuk-coronavirus-vulnerable-people-form-prod

  - name: smoke-test-prod
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-prod]
      - get: tests-image
        passed: [build-tests-image]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://coronavirus-vulnerable-people.service.gov.uk/live-in-england'
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes. If this fails, you should investigate immediately."
      - task: run-smoke-tests
        file: git-master/concourse/tasks/run-smoke-tests.yml
        params:
          TEST_URL: 'https://coronavirus-vulnerable-people.service.gov.uk'
