platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: govuk-coronavirus-vulnerable-people-tests-image
params:
  TEST_URL:
  RAILS_ENV: smoke_test
  METRICS_USERNAME: ((metrics-username))
  METRICS_PASSWORD: ((metrics-password))
inputs:
  - name: git-master
run:
  path: sh
  dir: git-master
  args:
    - '-c'
    - |
      bundle
      bundle exec rspec spec/features
