on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports: ["8000:8000"]

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle

    - run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        RAILS_ENV: test

    - run: bundle exec rake
      env:
        RAILS_ENV: test
